/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:336739:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:336739:




public void PauseButtonClick(GButton source, GEvent event) { //_CODE_:pauseButton:931158:

  if (buttonPressed == false){
  
    noLoop();
    buttonPressed = true;
    pauseButton.saveText("Resume");

}

  else{
    
   buttonPressed = false; 
   loop();
    
  }

}


public void slider1_change1(GSlider source, GEvent event) { //_CODE_:Pollution_Degree:319815:
  println("Pollution_Degree - GSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Pollution_Degree:319815:

public void custom_slider1_change1(GCustomSlider source, GEvent event) { //_CODE_:Cleansers_Number:351639:
  println("Cleansers_Number - GCustomSlider >> GEvent." + event + " @ " + millis());
} //_CODE_:Cleansers_Number:351639:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 3, 5, 80, 30);
  button1.setText("Reset");
  button1.addEventHandler(this, "button1_click1");
  pauseButton = new GButton(this, 106, 5, 80, 30);
  pauseButton.setText("Pause");
  pauseButton.addEventHandler(this, "PauseButtonClick");
  Pollution_Degree = new GSlider(this, 7, 46, 100, 40, 10.0);
  Pollution_Degree.setLimits(5.0, 1.0, 10.0);
  Pollution_Degree.setNumberFormat(G4P.DECIMAL, 2);
  Pollution_Degree.setOpaque(false);
  Pollution_Degree.addEventHandler(this, "slider1_change1");
  Cleansers_Number = new GCustomSlider(this, 7, 95, 100, 40, "grey_blue");
  Cleansers_Number.setLimits(15.0, 2.0, 30.0);
  Cleansers_Number.setNumberFormat(G4P.DECIMAL, 2);
  Cleansers_Number.setOpaque(false);
  Cleansers_Number.addEventHandler(this, "custom_slider1_change1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton pauseButton; 
GSlider Pollution_Degree; 
GCustomSlider Cleansers_Number; 
